### ISSUE TITLE
Nuclear Samples are not showing in the FNEI mod

### ISSUE THREAD

**Issue by ChurchOrganist** [pyanodon/pyfusionenergy#1]
Hi Pyanodon,

The Nuclear Sample product is not displaying a recipe in FNEI - I don't know whether this is something in FNEI mod or in this one - I have reported this also in the FNEI Github Issues - perhaps you could communicate to work out why?

FNEI Github is here.....
https://github.com/npo6ka/FNEI/issues

**Comment by Nexela** [comment]
Fixed in FNEI by the looks of it
