### ISSUE TITLE
Proposed Tech Tree rework

### ISSUE THREAD

**Issue by wesdotcool** [pyanodon/pyfusionenergy#10]
After looking through the techs individually, I created this diagram to illustrate several issues and how they can be fixed. I didn't provide all of the reasoning for each change to keep it succinct, but I can answer any questions on why the changes are proposed.

![pyFE Tech Tree Rework](https://user-images.githubusercontent.com/246963/131190223-3b35b918-b9d1-470a-831c-9fb285bb3dde.png)

One major question I have is about how this will work with pyHT. Helium, Molybdenum, and Vanadium are not needed (and not possible to actually create) until after prod science, but all of those are needed for c3 which is needed to make prod science (in pyHT). I'd like to hear your thoughts on that mismatch.

**Comment by oorzkws** [comment]
I'm going to close this since the tech tree has gone through a major restructure in the development version. Any issues of unlock order should be resolved now, but if there's other feedback you're welcome to open an issue when the beta releases (soon™).
