### ISSUE TITLE
Coal processing 3 prerequisites

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pyfusionenergy#12]
mods: PyCoal, PyFE
tech: Coal processing 3

Missing prerequisites:
- Advanced material processing 2 (Fuel rod for steam heating)

The Steam heating is unlocked at Coal processing 3, and the Heat exchanger is unlocked at Hydrocarbon cracking. These two should be unlocked at the same tech, whichever it is, and that tech will need the above prerequisite.

**Comment by ShadowGlass0** [comment]
The heat exchanger will also need the Cooling tower 1 prerequisite

**Comment by kingarthur91** [comment]
advanced material processing 2 is prereq of energy gen 3 which is a prereq of fusion 1 where ive stuck these due to no real need elsewhere. i did not alter cp3 as   its no longer connected to the issues in here
