### ISSUE TITLE
Diamond mining prerequisites

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pyfusionenergy#13]
mods: PyCoal, PyFE
tech: Diamond mining

Missing prerequisites:
- Excavation 1 (Ground borer needed for Grease table)

Also needs the Pressure pump (currently in Placeholder, recommended to add it to Advanced mining facilities and move the Vacuum recipe there too).

**Comment by kingarthur91** [comment]
see issue #11 for excavation 1. moved vacuum and the pump to advanced mining facilities
