### ISSUE TITLE
Boron

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pyfusionenergy#16]
Boron processing (or just Boron) should be its own tech, with the recipes Boron trioxide dust, Boron mixture, Boron, Boron carbide

Boron is only used in Fusion 4, and Boron carbide in all of the fusions (Blanket), so it should be production tech level.

Some other ideas for usages: https://en.wikipedia.org/wiki/Boron#Applications, 

So for example Boron could be an ingredient in Nuclear reactor, although that's Chemical science currently, so maybe not.
Boron carbide is added as ingredient to high tier buildings in PyRO, so it might also be added to buildings in PyFE, which are unlocked at Production science or later (Fusion reactors for example).

**Comment by ShadowGlass0** [comment]
Better idea:
Boron processing 1 (red science): Crystal mine, Diborane, Boric acid, Boron trioxide

Boron processing 2 (production science): Boron trioxide dust, Boron mixture, Boron, Boron carbide

**Comment by kingarthur91** [comment]
im ok with this but i think well need py to get us a boron tech icon as the current icons are all to small to upscale from 32x to 128x of tech icons
