### ISSUE TITLE
Clean up Vanadium tech

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pyfusionenergy#18]
Move Xyhiphoe stuff into its own tech:
- Phytoplankton farm
- Phytoplankton (optional: Move these two into their own tech, if we can find some other uses for it)
- Xyhiphoe pool
- Xyhiphoe blood
- Organic solvent (from Xyhiphoe blood)
- Methanol from wastewater
- Muddy sludge from wastewater

Because the Organic solvent and Methanol recipes this could be useful way before Vanadium, so this could be Chemical science or lower (but probably Chemical science).

Move the two log recipes using wastewater to Wood processing 3 (new tech)

**Comment by kingarthur91** [comment]
im not finding much of anything we could really use the phytoplankton for besides food like it already is. the rest can be done. just need to grab the tech icon from pyal and add the pyfe border to it
